DROP DATABASE IF EXISTS NotesApp;
CREATE DATABASE IF NOT EXISTS NotesApp;
USE NotesApp;
CREATE TABLE IF NOT EXISTS notes (
	id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

USE NotesApp;
DESCRIBE notes;

SELECT * FROM notes;